---
name: ci-gradle-standard

on:
  workflow_call:
    inputs:
      gradle_opts:
        description: Single string of gradle opts to pass via environment
        type: string
        default: -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"
        required: false
      gradle_switches:
        description: Single string of gradle switches to pass via commandline
        type: string
        default: --console=plain --info --stacktrace --no-daemon
        required: false
      java_version:
        description: Version of Java use
        type: string
        default: "11"
        required: false
    secrets:
      ossrh_username:
        required: true
      ossrh_token:
        required: true
      ossrh_signing_key:
        required: true
      ossrh_signing_password:
        required: true
      gradle_enterprise_access_key:
        description: Value of the Gradle Enterprise access token to use
        required: true

env:
  GRADLE_OPTS: ${{ inputs.gradle_opts }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'openrewrite'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set-up-jdk
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ inputs.java_version }}
          cache: gradle
      - name: build
        run: ./gradlew ${{ inputs.gradle_switches }} build test
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.gradle_enterprise_access_key }}
      - name: publish-tests
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "**/build/test-results/test/TEST-*.xml"

  publish-snapshots:
    needs: [build]
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && github.repository_owner == 'openrewrite'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set-up-jdk
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ inputs.java_version }}
          cache: gradle
      - name: publish-snapshots
        run: ./gradlew ${{ inputs.gradle_switches }} snapshot publish -PforceSigning -x test
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.ossrh_username }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ossrh_token }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ossrh_signing_key }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ossrh_signing_password }}
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.gradle_enterprise_access_key }}
