---
name: Moderne ingest

on:
  workflow_call:
    inputs:
      moderne_ingest_container_version:
        description: Version of the Moderne ingest container to use
        type: string
        default: java11-latest
        required: false
    secrets:
      moderne_api_access_token:
        description: The Moderne API access token to use for pushing the generated ASTs
        required: true

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: ingest
        uses: docker://moderne/ingest:${{ inputs.moderne_ingest_container_version }}
        env:
          MODERNE_API_ACCESS_TOKEN: ${{ secrets.moderne_api_access_token }}
